services:
  php:
    user: 1000:1000
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    volumes:
      - ./:/var/www
    ports:
      - 82:80
